# TODO: Edit this component to register more information about your repository with M-DEVx.
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  test: ${"name":"datapower server test1","destination":{"host":"github.com","owner":"TKH-Maybank-Organization","repo":"dpservice2"}}
  name: "datapower server test1"
  links:
    - url: https://githubbeta.maybank.com
      title: Github Maybank (Beta)
      icon: dashboard
  annotations:
    # TODO: Github CI/CD, Pull Request, Repository Info etc.
    github.com/project-slug: TKH-Maybank-Organization/datapower server test1
#    github.com/project-slug: MY-MAYBANK/datapower server test1
    # TODO: Add Enterprise sentry project ID
    sentry.io/project-slug: datapower server test1
#    sentry.io/project-slug: MY-MAYBANK/datapower server test1
    # TODO: Kubernetes: https://backstage.io/docs/features/kubernetes/configuration/
    backstage.io/kubernetes-id: banking-dev
    backstage.io/kubernetes-namespace: banking-dev
    backstage.io/kubernetes-label-selector: 'app=datapower server test1,component=banking-dev'
    backstage.io/techdocs-ref: dir:.

spec:
  type: service
  owner: group:developer
  lifecycle: experimental
  dependsOn:
    - resource:default/artists-db
  providesApis:
    - spotify
